version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./firebase-service-account.json:/app/firebase-service-account.json
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: produser123
      POSTGRES_DB: prod_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d  # init.sql dosyasını burada mount ediyoruz
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: